[package]
name = "poketoken-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "poke-token-bar"
path = "src/main.rs"

[dependencies]
poketoken-core = { path = "../core" }
clap.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
