#!/usr/bin/env python3
"""Generate crates/core/src/pool_gen.rs from PokéAPI.

Mirrors the macOS app's runtime data sources:
- base pool  : species 1..=649 with evolves_from_species == null, excluding Ditto (132)
               (PokeAPIClient.fetchBaseIndex GraphQL query)
- evolution trees: /evolution-chain/{base}, children with species id > 649 dropped
               (EvoLine.keepingAnimatedSprites, PokemonAssets.animatedSpeciesIDs = 1...649)
- names      : ko / en / ja-Hrkt(fallback ja) / es, per species on every chain
"""
import json
import re
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

BASE = "https://pokeapi.co/api/v2"
LANGS = {"ko", "en", "ja-Hrkt", "ja", "es"}
MAX_ID = 649
DITTO = 132
UA = {"User-Agent": "PokeTokenBar-gnome-port/0.1 (pool generation, one-off)"}

species_cache = {}
chain_cache = {}


def get(path):
    url = f"{BASE}/{path}"
    for attempt in range(5):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.loads(r.read().decode("utf-8"))
        except Exception as e:
            if attempt == 4:
                raise
            time.sleep(1.5 * (attempt + 1))
    raise RuntimeError("unreachable")


def fetch_species(i):
    if i in species_cache:
        return species_cache[i]
    d = get(f"pokemon-species/{i}")
    names = {}
    for n in d["names"]:
        lang = n["language"]["name"]
        if lang in LANGS:
            names[lang] = n["name"]
    species_cache[i] = {
        "id": i,
        "slug": d["name"],
        "capture_rate": d["capture_rate"],
        "is_legendary": d["is_legendary"],
        "is_mythical": d["is_mythical"],
        "evolves_from": (d.get("evolves_from_species") or {}).get("url"),
        "chain_url": d["evolution_chain"]["url"],
        "names": names,
    }
    return species_cache[i]


def fetch_chain(base_id):
    if base_id in chain_cache:
        return chain_cache[base_id]
    sp = fetch_species(base_id)
    d = get(sp["chain_url"].replace(BASE + "/", ""))
    chain_cache[base_id] = d
    return d


def chain_ids(link, out, keep):
    """Collect (species_id, [child species ids]) for ids in 1..=649 (animated filter)."""
    sid = int(link["species"]["url"].rsplit("/", 2)[1])
    if not keep or not (1 <= sid <= MAX_ID):
        return
    kids = []
    for c in link.get("evolves_to", []):
        chain_ids(c, out, keep)
        cid = int(c["species"]["url"].rsplit("/", 2)[1])
        if 1 <= cid <= MAX_ID:
            kids.append(cid)
    out.append((sid, tuple(kids)))


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    max_workers = 8
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        list(ex.map(fetch_species, range(1, MAX_ID + 1)))
    bases = [
        fetch_species(i)
        for i in range(1, MAX_ID + 1)
        if fetch_species(i)["evolves_from"] is None and i != DITTO
    ]
    bases.sort(key=lambda b: b["id"])
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        list(ex.map(fetch_chain, [b["id"] for b in bases]))

    # Evolution tree: all parent->children edges across every base chain.
    edges = {}
    all_chain_ids = set()
    for b in bases:
        out = []
        chain_ids(fetch_chain(b["id"])["chain"], out, keep=True)
        for sid, kids in out:
            all_chain_ids.add(sid)
            edges.setdefault(sid, set()).update(kids)
    for kids in edges.values():
        pass
    # Names needed for every species appearing in any kept tree + all bases.
    named_ids = all_chain_ids | {b["id"] for b in bases}
    # Keep species rows for the full 1..=649 range so slugs/names are complete.
    species_rows = [fetch_species(i) for i in range(1, MAX_ID + 1)]

    def ja_name(sp):
        n = sp["names"]
        return n.get("ja-Hrkt") or n.get("ja") or ""

    lines = []
    a = lines.append
    a("// GENERATED by scripts/gen_pool.py from PokéAPI (pokeapi.co) — DO NOT EDIT.")
    a("// Regenerate: python3 scripts/gen_pool.py > crates/core/src/pool_gen.rs")
    a("//")
    a(f"//! Gen I–V data snapshot: {MAX_ID} species, {len(bases)} hatchable bases")
    a(f"//! (bases = evolves_from null, excluding Ditto #{DITTO}, as in the macOS app's")
    a("//! baseSpeciesIndex). Evolution trees drop children outside 1..=649")
    a("//! (keepingAnimatedSprites / PokemonAssets.animatedSpeciesIDs).")
    a("")
    a("use crate::companion::Rarity;")
    a("")
    a("/// One species: official names in the four app languages (ja = ja-Hrkt, fallback ja)")
    a("/// plus the hatch-relevant flags (used to derive a line's rarity for species that are")
    a("/// not in the hatch pool, e.g. Ditto).")
    a("#[derive(Debug, Clone, Copy)]")
    a("pub struct SpeciesRow {")
    a("    pub id: u16,")
    a("    pub slug: &'static str,")
    a("    pub en: &'static str,")
    a("    pub ko: &'static str,")
    a("    pub ja: &'static str,")
    a("    pub es: &'static str,")
    a("    pub capture_rate: u16,")
    a("    pub legendary: bool,")
    a("    pub mythical: bool,")
    a("}")
    a("")
    a("pub const SPECIES: &[SpeciesRow] = &[")
    for sp in species_rows:
        n = sp["names"]
        a(
            f"    SpeciesRow {{ id: {sp['id']}, slug: \"{esc(sp['slug'])}\", "
            f"en: \"{esc(n.get('en', ''))}\", ko: \"{esc(n.get('ko', ''))}\", "
            f"ja: \"{esc(ja_name(sp))}\", es: \"{esc(n.get('es', ''))}\", "
            f"capture_rate: {sp['capture_rate']}, "
            f"legendary: {str(sp['is_legendary']).lower()}, "
            f"mythical: {str(sp['is_mythical']).lower()} }},"
        )
    a("];")
    a("")
    a("/// One hatchable base line: official capture rate + legendary/mythical flags")
    a("/// (rarity derives via `Rarity::from_capture_rate`).")
    a("#[derive(Debug, Clone, Copy)]")
    a("pub struct BaseRow {")
    a("    pub id: u16,")
    a("    pub slug: &'static str,")
    a("    pub capture_rate: u16,")
    a("    pub legendary: bool,")
    a("    pub mythical: bool,")
    a("    pub rarity: Rarity,")
    a("}")
    a("")
    a("pub const BASES: &[BaseRow] = &[")
    for b in bases:
        rar = (
            "Legendary"
            if b["is_legendary"] or b["is_mythical"]
            else "Rare" if b["capture_rate"] <= 45
            else "Uncommon" if b["capture_rate"] <= 120
            else "Common"
        )
        a(
            f"    BaseRow {{ id: {b['id']}, slug: \"{esc(b['slug'])}\", "
            f"capture_rate: {b['capture_rate']}, legendary: {str(b['is_legendary']).lower()}, "
            f"mythical: {str(b['is_mythical']).lower()}, rarity: Rarity::{rar} }},"
        )
    a("];")
    a("")
    a("/// Evolution-tree edges (parent species id -> child species ids), covering every")
    a("/// species reachable from a base in 1..=649. Sorted by parent id.")
    a("pub const CHILDREN: &[(u16, &[u16])] = &[")
    for sid in sorted(edges):
        kids = ", ".join(str(k) for k in sorted(edges[sid]))
        a(f"    ({sid}, &[{kids}]),")
    a("];")
    a("")
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
