//! The full Gen I–V evolution-line pool (port of the macOS app's PokéAPI-backed pool).
//!
//! The macOS app resolves the pool at runtime from PokéAPI: every base species
//! (`evolves_from_species == null`, ids 1–649, Ditto #132 excluded — it is reserved for the
//! disguise reveal) with its official `capture_rate` as the hatch weight, its evolution-chain
//! tree (children outside 1–649 dropped, `keepingAnimatedSprites`), and per-language names.
//! This port embeds the same snapshot as a static table ([`crate::pool_gen`], regenerated by
//! `scripts/gen_pool.py`) so hatching is fully offline and deterministic.
//!
//! Selection semantics are a faithful port of `CompanionStore.chooseBase`:
//! - a premium egg's tier pre-filters candidates by `Rarity::includes(capture_rate)`
//!   (the capture-rate ceiling is the tier floor, so legendaries naturally stay in "rare+");
//! - weight = official capture rate, halved (min 1) when a final form of that base was already
//!   collected (`collectedFinals` "base:final" entries) — an uncollected boost that keeps
//!   re-hatching/shiny hunting open;
//! - exactly one roll over the cumulative weights (no re-rolls, deterministic time bound).

use crate::companion::Rarity;
use crate::i18n::Language;
use crate::pool_gen::{BaseRow, SpeciesRow, BASES, CHILDREN, SPECIES};

/// Highest species id with animated Gen-V assets (`PokemonAssets.animatedSpeciesIDs`).
pub const MAX_SPECIES_ID: u16 = 649;

/// A hatchable evolution line (base species + derived metadata).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LineMeta {
    pub base_id: u16,
    pub slug: &'static str,
    /// English display name (sprite lookup uses this, never the localized name).
    pub en: &'static str,
    pub rarity: Rarity,
    pub capture_rate: u16,
}

pub fn base_count() -> usize {
    BASES.len()
}

/// The full hatch pool (Ditto excluded, as in `fetchBaseIndex`).
pub fn bases() -> &'static [BaseRow] {
    BASES
}

pub fn species_by_id(id: u16) -> Option<&'static SpeciesRow> {
    SPECIES.iter().find(|s| s.id == id)
}

pub fn species_by_slug(slug: &str) -> Option<&'static SpeciesRow> {
    SPECIES.iter().find(|s| s.slug == slug)
}

pub fn base_by_id(id: u16) -> Option<&'static BaseRow> {
    BASES.iter().find(|b| b.id == id)
}

pub fn base_by_slug(slug: &str) -> Option<&'static BaseRow> {
    BASES.iter().find(|b| b.slug == slug)
}

/// Children of a species in the evolution trees (`&[]` for leaves / unknown ids).
pub fn children_of(id: u16) -> &'static [u16] {
    // CHILDREN is sorted by parent id (generated); a linear scan over ~330 edges is cheap
    // and keeps the table layout trivial to regenerate.
    CHILDREN
        .iter()
        .find(|(parent, _)| *parent == id)
        .map(|(_, kids)| *kids)
        .unwrap_or(&[])
}

pub fn line_by_id(base_id: u16) -> Option<LineMeta> {
    let s = species_by_id(base_id)?;
    // Hatchable bases carry their precomputed rarity; any other species (notably Ditto,
    // which is excluded from the pool and only appears via the disguise reveal) derives it
    // the same way the macOS app does: official capture rate + legendary/mythical flags.
    let (rarity, capture_rate) = match base_by_id(base_id) {
        Some(b) => (b.rarity, b.capture_rate),
        None => (
            Rarity::from_capture_rate(s.capture_rate as i32, s.legendary, s.mythical),
            s.capture_rate,
        ),
    };
    Some(LineMeta {
        base_id,
        slug: s.slug,
        en: s.en,
        rarity,
        capture_rate,
    })
}

/// Line for a base slug; also resolves non-pool species like `ditto` (disguise reveal).
pub fn line_by_slug(slug: &str) -> Option<LineMeta> {
    let s = species_by_slug(slug)?;
    line_by_id(s.id)
}

/// Localized species name: the language's official name, falling back to English, then `#id`
/// (port of `AppLanguage.resolveName` + `EvoLine.localizedName`).
pub fn localized_name(id: u16, lang: Language) -> String {
    match species_by_id(id) {
        Some(s) => match lang {
            Language::Ko => s.ko,
            Language::Ja => s.ja,
            Language::Es => s.es,
            Language::En => s.en,
        }
        .if_empty(s.en)
        .if_empty(format!("#{id}")),
        None => format!("#{id}"),
    }
}

/// English name (`#id` fallback) — used for sprite slugs and JSON.
pub fn en_name(id: u16) -> String {
    species_by_id(id).map(|s| s.en.to_string()).unwrap_or_else(|| format!("#{id}"))
}

trait IfEmpty {
    fn if_empty(self, fallback: impl Into<String>) -> String;
}

impl IfEmpty for &str {
    fn if_empty(self, fallback: impl Into<String>) -> String {
        if self.is_empty() {
            fallback.into()
        } else {
            self.to_string()
        }
    }
}

/// Every final-form id reachable from `id` (port of `EvoNode.finalIDs`).
pub fn final_ids_of(id: u16) -> Vec<u16> {
    let kids = children_of(id);
    if kids.is_empty() {
        vec![id]
    } else {
        kids.iter().flat_map(|id| final_ids_of(*id)).collect()
    }
}

/// The unique tree path from `root` to `target` (None when `target` is not in the subtree).
pub fn path_from_root_to(root: u16, target: u16) -> Option<Vec<u16>> {
    let mut path = vec![root];
    if root == target {
        return Some(path);
    }
    for kid in children_of(root) {
        if let Some(mut rest) = path_from_root_to(*kid, target) {
            path.append(&mut rest);
            return Some(path);
        }
    }
    None
}

/// Longest root-to-leaf path length in forms (port of `EvoNode.depth` — used for the Ditto
/// disguise "≥2 forms" gate, which in Swift consults `line.totalForms` = tree depth).
pub fn tree_depth(id: u16) -> u16 {
    1 + children_of(id).iter().map(|c| tree_depth(*c)).max().unwrap_or(0)
}

/// Longest prefix of `ids` that actually continues from `root` (port of `longestValidPath`).
/// A first id that is not the root resets to the root alone (corrupt-save recovery).
pub fn longest_valid_path(ids: &[u16], root: u16) -> Vec<u16> {
    let mut path = vec![root];
    let mut node = root;
    if ids.first() != Some(&root) {
        return path;
    }
    for id in &ids[1..] {
        let is_child = children_of(node).iter().any(|c| c == id);
        if !is_child {
            break;
        }
        path.push(*id);
        node = *id;
    }
    path
}

/// Pick the next evolution among `node`'s children (port of `pickPlannedChild`): prefer
/// children whose final forms include an *uncollected* "base:final"; then one uniform roll.
pub fn pick_planned_child(node: u16, base: u16, collected: &[String], roll: u64) -> u16 {
    let kids = children_of(node);
    let owned = |final_id: u16| {
        let key = format!("{base}:{final_id}");
        collected.iter().any(|c| c == &key)
    };
    let fresh: Vec<u16> = kids
        .iter()
        .copied()
        .filter(|ch| final_ids_of(*ch).iter().any(|f| !owned(*f)))
        .collect();
    let pool: &[u16] = if fresh.is_empty() { kids } else { &fresh };
    pool[(roll % pool.len() as u64) as usize]
}

/// A full evolution route from `root` to a leaf (port of `makeEvolutionPlan`). One RNG roll
/// per branching level; straight lines consume none.
pub fn make_evolution_plan(root: u16, collected: &[String], roll_source: &mut dyn Roll) -> Vec<u16> {
    let mut plan = vec![root];
    let mut node = root;
    while !children_of(node).is_empty() {
        let kids = children_of(node);
        let next = if kids.len() == 1 {
            kids[0]
        } else {
            pick_planned_child(node, root, collected, roll_source.next())
        };
        plan.push(next);
        node = next;
    }
    plan
}

/// Normalization of a persisted (path, planned) pair against the current tree (port of
/// `normalizedEvolutionState`): reuse the saved plan only when it is complete and still
/// valid, otherwise re-plan from the realized node. Returns (path, planned, stage_index).
pub fn normalize_evolution(
    saved_path: &[u16],
    saved_planned: &[u16],
    root: u16,
    collected: &[String],
    roll_source: &mut dyn Roll,
) -> (Vec<u16>, Vec<u16>, usize) {
    let realized = longest_valid_path(saved_path, root);
    let candidate = longest_valid_path(saved_planned, root);
    let can_reuse = candidate == saved_planned
        && candidate.starts_with(&realized)
        && children_of(*candidate.last().unwrap_or(&root)).is_empty();
    let planned = if can_reuse {
        candidate
    } else {
        let suffix = make_evolution_plan(*realized.last().unwrap_or(&root), collected, roll_source);
        let mut plan = realized.clone();
        plan.extend(suffix.iter().skip(1));
        plan
    };
    let stage = realized.len().saturating_sub(1);
    (realized, planned, stage)
}

/// One hatch roll (port of `chooseBase`, weighted path only — the REST fallback is
/// meaningless for a static pool). Returns None when a guaranteed tier has no candidates.
pub fn choose_base(tier: Option<Rarity>, collected: &[String], roll_source: &mut dyn Roll) -> Option<u16> {
    let index: Vec<&BaseRow> = match tier {
        Some(t) => BASES.iter().filter(|b| t.includes(b.capture_rate as i32)).collect(),
        None => BASES.iter().collect(),
    };
    if index.is_empty() {
        return None;
    }
    let weights: Vec<u64> = index
        .iter()
        .map(|b| {
            let prefix = format!("{}:", b.id);
            let w = (b.capture_rate as u64).max(1);
            if collected.iter().any(|c| c.starts_with(&prefix)) {
                (w / 2).max(1)
            } else {
                w
            }
        })
        .collect();
    let total: u64 = weights.iter().sum();
    let mut r = roll_source.next() % total;
    for (i, w) in weights.iter().enumerate() {
        if *w > r {
            return Some(index[i].id);
        }
        r -= w;
    }
    index.last().map(|b| b.id)
}

/// An RNG stream that yields successive u64s (the state's persisted LCG).
pub trait Roll {
    fn next(&mut self) -> u64;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::companion::Rarity;

    /// Deterministic 64-bit LCG for tests (same step as the companion's persisted seed).
    struct Lcg(u64);
    impl Roll for Lcg {
        fn next(&mut self) -> u64 {
            let mut x = self.0;
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            self.0 = x;
            x
        }
    }

    #[test]
    fn pool_snapshot_shape() {
        // Generated snapshot invariants (328 = Gen I–V bases, Ditto #132 excluded).
        assert_eq!(base_count(), 328);
        assert_eq!(SPECIES.len(), 649);
        assert!(BASES.iter().all(|b| b.id <= MAX_SPECIES_ID));
        assert!(!BASES.iter().any(|b| b.id == 132), "Ditto is excluded from the hatch pool");
        // Rarities derive from the official capture rate / flags.
        let caterpie = base_by_id(10).unwrap();
        assert_eq!(caterpie.rarity, Rarity::Common);
        let mewtwo = base_by_id(150).unwrap();
        assert_eq!(mewtwo.rarity, Rarity::Legendary);
        let bulbasaur = base_by_id(1).unwrap();
        assert_eq!(bulbasaur.rarity, Rarity::Rare); // capture_rate 45
    }

    #[test]
    fn every_base_resolves_names_and_tree() {
        for b in BASES {
            let line = line_by_id(b.id).unwrap_or_else(|| panic!("base {} unresolvable", b.id));
            assert_eq!(line.slug, b.slug);
            assert!(!line.en.is_empty());
            for lang in [Language::En, Language::Ko, Language::Ja, Language::Es] {
                let name = localized_name(b.id, lang);
                assert!(!name.is_empty() && !name.starts_with('#'), "{:?} {lang:?}", line.en);
            }
            // Every base has at least itself as a final-form candidate.
            assert!(!final_ids_of(b.id).is_empty());
        }
    }

    #[test]
    fn branching_lines() {
        // Eevee (133) has its seven Gen I–V evolutions (Sylveon #700 filtered out).
        assert_eq!(children_of(133).to_vec(), vec![134, 135, 136, 196, 197, 470, 471]);
        assert_eq!(children_of(236).to_vec(), vec![106, 107, 237]); // Tyrogue
        assert_eq!(children_of(361).to_vec(), vec![362, 478]); // Snorunt
    }

    #[test]
    fn straight_line_plan_consumes_no_rolls() {
        let mut r = Lcg(7);
        let before = r.0;
        let plan = make_evolution_plan(1, &[], &mut r);
        assert_eq!(plan, vec![1, 2, 3]);
        assert_eq!(r.0, before, "no branches → no rolls");
    }

    #[test]
    fn plan_is_deterministic_and_uncollected_preferring() {
        let empty: Vec<String> = vec![];
        let a = make_evolution_plan(133, &empty, &mut Lcg(42));
        let b = make_evolution_plan(133, &empty, &mut Lcg(42));
        assert_eq!(a, b, "same seed → same plan");
        assert_eq!(a.first(), Some(&133));
        assert!(children_of(*a.last().unwrap()).is_empty(), "plan must end at a leaf");
        // Collecting that final biases the next roll toward other branches.
        let collected = vec![format!("133:{}", a.last().unwrap())];
        let c = make_evolution_plan(133, &collected, &mut Lcg(42));
        assert_eq!(c.first(), Some(&133));
        assert!(children_of(*c.last().unwrap()).is_empty());
    }

    #[test]
    fn choose_base_respects_tier_guarantee() {
        for i in 0..200 {
            let mut r = Lcg(0x9e3779b97f4a7c15 + i as u64);
            let id = choose_base(Some(Rarity::Rare), &[], &mut r).expect("rare+ pool non-empty");
            let rarity = line_by_id(id).unwrap().rarity;
            assert!(
                rarity.sort_rank() >= Rarity::Rare.sort_rank(),
                "rolled {rarity:?} below guaranteed rare"
            );
        }
        // Common is never "guaranteed" in the shop; None tier uses the full pool.
        let mut r = Lcg(1);
        assert!(choose_base(None, &[], &mut r).is_some());
    }

    #[test]
    fn collected_base_gets_half_weight() {
        // A single-entry pool pair: with the base uncollected the weight is its capture rate;
        // collected halves it (min 1). Exercise through two candidates' relative odds.
        let mut r = Lcg(5);
        let id = choose_base(None, &[], &mut r);
        assert!(id.is_some());
        let mut r2 = Lcg(5);
        let collected: Vec<String> = BASES.iter().map(|b| format!("{}:{}", b.id, b.id)).collect();
        let id2 = choose_base(None, &collected, &mut r2);
        // With every base collected at weight ≥1 the roll still resolves deterministically.
        assert!(id2.is_some());
    }

    #[test]
    fn longest_valid_path_recovers_corrupt_paths() {
        assert_eq!(longest_valid_path(&[1, 2, 3], 1), vec![1, 2, 3]);
        assert_eq!(longest_valid_path(&[1, 3], 1), vec![1]); // 3 is not a child of 1
        assert_eq!(longest_valid_path(&[2, 3], 1), vec![1]); // wrong root resets
        assert_eq!(longest_valid_path(&[], 1), vec![1]);
    }

    #[test]
    fn normalize_reuses_complete_plans_and_replans_broken_ones() {
        let mut r = Lcg(9);
        let (path, planned, stage) = normalize_evolution(&[1, 2], &[1, 2, 3], 1, &[], &mut r);
        assert_eq!(path, vec![1, 2]);
        assert_eq!(planned, vec![1, 2, 3], "complete valid plan is reused");
        assert_eq!(stage, 1);

        let mut r = Lcg(9);
        let (path, planned, stage) = normalize_evolution(&[1, 2], &[1, 2], 1, &[], &mut r);
        assert_eq!(path, vec![1, 2]);
        assert_eq!(planned, vec![1, 2, 3], "incomplete plan is extended to a leaf");
        assert_eq!(stage, 1);
    }
}
